"""Helpers to read/write runtime app settings.

Defines well-known setting keys + accessors. Both async (DB session) and sync
(direct sqlite) flavours are exposed because PDF rendering may run from
contexts that don't have an async session handy.
"""

import logging
import sqlite3
import string
from datetime import datetime
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings as app_config
from app.models.app_setting import AppSetting

logger = logging.getLogger(__name__)

# ----- well-known keys -----
KEY_PDF_AUTHOR_SIGNATURE = "pdf.author_signature"
KEY_PDF_AUTHOR_AFFILIATION = "pdf.author_affiliation"
KEY_PDF_AUTHOR_EXTRA = "pdf.author_extra"
KEY_PDF_FOOTER_TEMPLATE = "pdf.footer_template"

DEFAULTS: dict[str, str] = {
    KEY_PDF_AUTHOR_SIGNATURE: "",
    KEY_PDF_AUTHOR_AFFILIATION: "",
    KEY_PDF_AUTHOR_EXTRA: "",
    KEY_PDF_FOOTER_TEMPLATE: "",
}

# Used when both the template and the signature fields are empty.
DEFAULT_FOOTER_TEMPLATE = "Generated by FL Research Monitor — {timestamp}"


# ----- async (preferred when called from API endpoints) -----

async def get_setting(db: AsyncSession, key: str, default: str | None = None) -> str:
    item = await db.get(AppSetting, key)
    if item and item.value is not None:
        return item.value
    return default if default is not None else DEFAULTS.get(key, "")


async def set_setting(db: AsyncSession, key: str, value: str) -> None:
    item = await db.get(AppSetting, key)
    if item:
        item.value = value
        item.updated_at = datetime.utcnow()
    else:
        db.add(AppSetting(key=key, value=value, updated_at=datetime.utcnow()))
    await db.commit()


async def get_all_settings(db: AsyncSession) -> dict[str, str]:
    res = await db.execute(select(AppSetting))
    items = {row.key: (row.value or "") for row in res.scalars().all()}
    # Fill defaults for known keys not yet stored
    for k, default in DEFAULTS.items():
        items.setdefault(k, default)
    return items


# ----- sync (for code paths without an async session) -----

def _resolve_db_path() -> str:
    """Pull the sqlite file path from DATABASE_URL config."""
    url = app_config.database_url
    if url.startswith("sqlite+aiosqlite:///"):
        return url.replace("sqlite+aiosqlite:///", "", 1)
    if url.startswith("sqlite:///"):
        return url.replace("sqlite:///", "", 1)
    return "data/db/research_monitor.db"


def get_setting_sync(key: str, default: str | None = None) -> str:
    """Read a setting via direct sqlite — usable from sync PDF generators."""
    try:
        db_path = _resolve_db_path()
        if not Path(db_path).exists():
            return default if default is not None else DEFAULTS.get(key, "")
        conn = sqlite3.connect(db_path)
        try:
            row = conn.execute(
                "SELECT value FROM app_settings WHERE key = ?", (key,)
            ).fetchone()
            if row and row[0] is not None:
                return row[0]
        finally:
            conn.close()
    except Exception as e:
        logger.warning(f"get_setting_sync({key}) failed: {e}")
    return default if default is not None else DEFAULTS.get(key, "")


# ----- PDF footer rendering -----

class _SafeFormatDict(dict):
    """Format mapping that leaves unknown placeholders literal instead of raising."""
    def __missing__(self, key):
        return "{" + key + "}"


def _safe_format(template: str, **kwargs) -> str:
    """Apply str.format on a template, ignoring unknown placeholders."""
    try:
        return string.Formatter().vformat(template, (), _SafeFormatDict(**kwargs))
    except (IndexError, ValueError):
        # Malformed template (stray { or }) — return raw so the user notices
        return template


def _esc_latex_value(s: str) -> str:
    """Escape special LaTeX characters in a value being interpolated into the
    footer template. The TEMPLATE itself is not escaped — it's authored by the
    user as plain LaTeX-aware text."""
    if not s:
        return ""
    return (
        s.replace("\\", "\\textbackslash{}")
         .replace("&", "\\&")
         .replace("%", "\\%")
         .replace("#", "\\#")
         .replace("_", "\\_")
         .replace("$", "\\$")
         .replace("{", "\\{")
         .replace("}", "\\}")
    )


def render_pdf_footer(latex: bool = False, *, signature: str | None = None,
                       affiliation: str | None = None, extra: str | None = None,
                       template: str | None = None) -> str:
    """Render the configurable PDF footer line.

    Reads pdf.footer_template + pdf.author_{signature,affiliation,extra} from
    app_settings (or accepts overrides for testing/preview), substitutes the
    {signature} {affiliation} {extra} {timestamp} placeholders, and returns
    a single line of text.

    If `latex=True`, the placeholder VALUES are escaped for LaTeX. The template
    itself is rendered as-is (typed by the user as plain LaTeX-aware text).

    Smart default: if no template is set,
    - and at least one author field is filled → join the filled fields with " — "
    - otherwise → fall back to "Generated by FL Research Monitor — {timestamp}"
    """
    sig = signature if signature is not None else (get_setting_sync(KEY_PDF_AUTHOR_SIGNATURE, "") or "")
    aff = affiliation if affiliation is not None else (get_setting_sync(KEY_PDF_AUTHOR_AFFILIATION, "") or "")
    ext = extra if extra is not None else (get_setting_sync(KEY_PDF_AUTHOR_EXTRA, "") or "")
    tpl = template if template is not None else (get_setting_sync(KEY_PDF_FOOTER_TEMPLATE, "") or "")

    sig = sig.strip()
    aff = aff.strip()
    ext = ext.strip()
    tpl = tpl.strip()
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    if not tpl:
        # No explicit template — pick a sensible default based on which fields are set
        parts = []
        if sig: parts.append("{signature}")
        if aff: parts.append("{affiliation}")
        if ext: parts.append("{extra}")
        if parts:
            tpl = " — ".join(parts)
        else:
            tpl = DEFAULT_FOOTER_TEMPLATE

    if latex:
        rendered = _safe_format(
            tpl,
            signature=_esc_latex_value(sig),
            affiliation=_esc_latex_value(aff),
            extra=_esc_latex_value(ext),
            timestamp=timestamp,
            align_right="\\hfill",
        )
        # If the user used {align_right}, wrap the whole footer in a fixed-width
        # hbox so that \hfill can actually push content to the right margin.
        if "\\hfill" in rendered:
            rendered = "\\hbox to \\linewidth{" + rendered + "}"
        return rendered
    # Plain text: there's no real right alignment, so {align_right} becomes a
    # tab + spacer that visually separates left and right blocks.
    return _safe_format(
        tpl,
        signature=sig,
        affiliation=aff,
        extra=ext,
        timestamp=timestamp,
        align_right="    \u2003    ",  # tab-like spacer (em-space surrounded by spaces)
    )
