"""Individual paper analysis report generator — HTML + PDF."""

import logging
import re
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, BaseLoader
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.config import settings
from app.models.paper import Paper, PaperSource
from app.models.topic import PaperTopic, Topic
from app.models.analysis import SyntheticAnalysis

logger = logging.getLogger(__name__)


def _pdf_footer_text() -> str:
    """Build the LaTeX footer line, including the configurable author signature.

    Reads pdf.author_signature / pdf.author_affiliation from app_settings.
    Falls back to plain 'Generated by FL Research Monitor' if no signature is set.
    """
    from app.services.app_settings import (
        get_setting_sync,
        KEY_PDF_AUTHOR_SIGNATURE,
        KEY_PDF_AUTHOR_AFFILIATION,
    )
    sig = (get_setting_sync(KEY_PDF_AUTHOR_SIGNATURE, "") or "").strip()
    aff = (get_setting_sync(KEY_PDF_AUTHOR_AFFILIATION, "") or "").strip()
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    # Escape LaTeX specials in signature/affiliation
    def _e(s: str) -> str:
        return s.replace('&', '\\&').replace('%', '\\%').replace('#', '\\#').replace('_', '\\_').replace('$', '\\$')
    if sig:
        line = _e(sig) + (" --- " + _e(aff) if aff else "")
        return f"Reviewed by {line} \\quad\\textbar\\quad Generated by FL Research Monitor --- {generated_at}"
    return f"Generated by FL Research Monitor --- {generated_at}"


def _pdf_footer_text_plain() -> str:
    """Plain-text version of the footer (for HTML report)."""
    from app.services.app_settings import (
        get_setting_sync,
        KEY_PDF_AUTHOR_SIGNATURE,
        KEY_PDF_AUTHOR_AFFILIATION,
    )
    sig = (get_setting_sync(KEY_PDF_AUTHOR_SIGNATURE, "") or "").strip()
    aff = (get_setting_sync(KEY_PDF_AUTHOR_AFFILIATION, "") or "").strip()
    if sig:
        line = sig + (f" — {aff}" if aff else "")
        return f"Reviewed by {line} · Generated by FL Research Monitor"
    return "Generated by FL Research Monitor"

# Keyword category mapping
KEYWORD_CATEGORIES = {
    "FL Core": {
        "color": "#6366f1",
        "bg": "rgba(99,102,241,0.15)",
        "terms": [
            "federated learning", "fedavg", "fedprox", "federated averaging",
            "federated optimization", "aggregation", "collaborative learning",
            "distributed learning", "model aggregation", "fedsgd", "scaffold",
            "fednova", "communication round",
        ],
    },
    "Privacy": {
        "color": "#ef4444",
        "bg": "rgba(239,68,68,0.15)",
        "terms": [
            "differential privacy", "privacy", "epsilon", "privacy budget",
            "secure aggregation", "homomorphic encryption", "privacy-preserving",
            "data protection", "anonymization", "gdpr",
        ],
    },
    "Healthcare": {
        "color": "#22c55e",
        "bg": "rgba(34,197,94,0.15)",
        "terms": [
            "healthcare", "clinical", "medical", "hospital", "ehr",
            "electronic health record", "patient", "diagnosis", "imaging",
            "health data", "ehds", "biomedical", "pharmaceutical", "drug",
        ],
    },
    "Systems": {
        "color": "#f59e0b",
        "bg": "rgba(245,158,11,0.15)",
        "terms": [
            "edge computing", "iot", "communication efficiency", "bandwidth",
            "latency", "scalability", "heterogeneous", "resource", "network",
            "distributed system", "cloud", "satellite", "6g", "5g",
        ],
    },
    "Methods": {
        "color": "#8b5cf6",
        "bg": "rgba(139,92,246,0.15)",
        "terms": [
            "experimental", "benchmark", "simulation", "framework", "survey",
            "deep learning", "convolutional", "reinforcement learning",
            "neural network", "transformer", "attention", "optimization",
        ],
    },
}


def categorize_keyword(keyword: str) -> tuple[str, str, str]:
    """Return (category, color, bg_color) for a keyword."""
    kw_lower = keyword.lower()
    for cat_name, cat_info in KEYWORD_CATEGORIES.items():
        for term in cat_info["terms"]:
            if term in kw_lower or kw_lower in term:
                return cat_name, cat_info["color"], cat_info["bg"]
    return "Other", "#6b6b80", "rgba(107,107,128,0.15)"


def markdown_to_html(md_text: str) -> str:
    """Convert markdown analysis text to HTML with tables and math support."""
    if not md_text:
        return ""

    import markdown

    # Protect LaTeX math from markdown processing
    # Block math: $$...$$ → placeholder
    math_blocks: list[str] = []
    def _save_block_math(m: re.Match) -> str:
        math_blocks.append(m.group(1))
        return f"MATHBLOCK_{len(math_blocks) - 1}_ENDMATH"

    text = re.sub(r'\$\$(.+?)\$\$', _save_block_math, md_text, flags=re.DOTALL)

    # Inline math: $...$ → placeholder (but not $$)
    math_inlines: list[str] = []
    def _save_inline_math(m: re.Match) -> str:
        math_inlines.append(m.group(1))
        return f"MATHINLINE_{len(math_inlines) - 1}_ENDMATH"

    text = re.sub(r'(?<!\$)\$([^\$\n]+?)\$(?!\$)', _save_inline_math, text)

    # Convert markdown to HTML using python-markdown with extensions
    html = markdown.markdown(
        text,
        extensions=["tables", "fenced_code", "nl2br"],
    )

    # Restore block math (keep LaTeX for MathJax rendering)
    for i, formula in enumerate(math_blocks):
        html = html.replace(
            f"MATHBLOCK_{i}_ENDMATH",
            f'<div class="math-block">$${formula}$$</div>'
        )

    # Restore inline math (keep LaTeX for MathJax rendering)
    for i, formula in enumerate(math_inlines):
        html = html.replace(
            f"MATHINLINE_{i}_ENDMATH",
            f'<span class="math-inline">${formula}$</span>'
        )

    return html


def _latex_to_html_math(formula: str, block: bool = False) -> str:
    """Convert LaTeX math to readable HTML without requiring JavaScript."""
    f = formula.strip()

    # Common LaTeX → HTML replacements
    replacements = [
        (r'\\frac\{([^}]+)\}\{([^}]+)\}', r'(\1)/(\2)'),
        (r'\\sum_\{([^}]+)\}\^\{([^}]+)\}', r'Σ<sub>\1</sub><sup>\2</sup>'),
        (r'\\sum', 'Σ'),
        (r'\\prod', 'Π'),
        (r'\\int', '∫'),
        (r'\\infty', '∞'),
        (r'\\alpha', 'α'), (r'\\beta', 'β'), (r'\\gamma', 'γ'),
        (r'\\delta', 'δ'), (r'\\epsilon', 'ε'), (r'\\theta', 'θ'),
        (r'\\lambda', 'λ'), (r'\\mu', 'μ'), (r'\\sigma', 'σ'),
        (r'\\pi', 'π'), (r'\\phi', 'φ'), (r'\\omega', 'ω'),
        (r'\\Delta', 'Δ'), (r'\\Sigma', 'Σ'), (r'\\Omega', 'Ω'),
        (r'\\nabla', '∇'), (r'\\partial', '∂'),
        (r'\\leq', '≤'), (r'\\geq', '≥'), (r'\\neq', '≠'),
        (r'\\approx', '≈'), (r'\\times', '×'), (r'\\cdot', '·'),
        (r'\\in', '∈'), (r'\\notin', '∉'), (r'\\subset', '⊂'),
        (r'\\rightarrow', '→'), (r'\\leftarrow', '←'), (r'\\Rightarrow', '⇒'),
        (r'\\forall', '∀'), (r'\\exists', '∃'),
        (r'\\sqrt\{([^}]+)\}', r'√(\1)'),
        (r'\\mathbb\{([^}]+)\}', r'\1'),
        (r'\\mathcal\{([^}]+)\}', r'\1'),
        (r'\\mathrm\{([^}]+)\}', r'\1'),
        (r'\\text\{([^}]+)\}', r'\1'),
        (r'\\textbf\{([^}]+)\}', r'<strong>\1</strong>'),
        (r'\\ell', 'ℓ'),
        (r'\^(\w)', r'<sup>\1</sup>'),
        (r'\^\{([^}]+)\}', r'<sup>\1</sup>'),
        (r'_(\w)', r'<sub>\1</sub>'),
        (r'_\{([^}]+)\}', r'<sub>\1</sub>'),
        (r'\\,', ' '),
        (r'\\;', ' '),
        (r'\\quad', '  '),
        (r'\\\\', '<br>'),
    ]

    for pattern, repl in replacements:
        f = re.sub(pattern, repl, f)

    # Remove remaining backslash commands
    f = re.sub(r'\\[a-zA-Z]+', '', f)
    # Clean up braces
    f = f.replace('{', '').replace('}', '')

    return f


PAPER_REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="it">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Analysis Report — {{ paper.title[:80] }}</title>
<script>
window.MathJax = {
  tex: { inlineMath: [['$','$'], ['\\\\(','\\\\)']], displayMath: [['$$','$$'], ['\\\\[','\\\\]']] },
  options: { skipHtmlTags: ['script','noscript','style','textarea'] }
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" async></script>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background: #0a0a0f; color: #e8e8f0;
    max-width: 800px; margin: 0 auto; padding: 32px 24px;
    line-height: 1.6; overflow-wrap: anywhere; word-break: break-word;
  }
  a { color: #6366f1; text-decoration: none; }
  a:hover { text-decoration: underline; }

  /* Header */
  .report-header {
    border-bottom: 2px solid #2a2a3e;
    padding-bottom: 24px;
    margin-bottom: 24px;
  }
  .report-title {
    font-size: 20px; font-weight: 700; line-height: 1.4;
    margin-bottom: 12px;
  }
  .report-meta {
    display: grid; grid-template-columns: auto 1fr;
    gap: 4px 16px; font-size: 12px; color: #a0a0b8;
  }
  .meta-label { color: #6b6b80; font-weight: 500; }

  /* Keywords */
  .keywords-section {
    background: #12121a; border: 1px solid #2a2a3e;
    border-radius: 12px; padding: 16px; margin-bottom: 24px;
  }
  .keywords-title {
    font-size: 13px; font-weight: 600; margin-bottom: 12px;
    color: #6b6b80; text-transform: uppercase; letter-spacing: 0.5px;
  }
  .keyword-tag {
    display: inline-block; font-size: 11px; padding: 3px 10px;
    border-radius: 20px; margin: 3px 4px 3px 0; font-weight: 500;
  }
  .keyword-category {
    margin-top: 12px; padding-top: 12px;
    border-top: 1px solid #2a2a3e;
  }
  .category-label {
    font-size: 11px; font-weight: 600; margin-bottom: 6px;
    display: flex; align-items: center; gap: 6px;
  }
  .category-dot {
    width: 8px; height: 8px; border-radius: 50%;
    display: inline-block;
  }

  /* Analysis sections */
  .analysis-content {
    background: #12121a; border: 1px solid #2a2a3e;
    border-radius: 12px; padding: 24px; margin-bottom: 16px;
    overflow-wrap: anywhere; word-break: break-word;
  }
  .analysis-content h3 {
    font-size: 15px; color: #6366f1; margin: 24px 0 10px;
    padding-bottom: 6px; border-bottom: 1px solid #2a2a3e;
  }
  .analysis-content h3:first-child { margin-top: 0; }
  .analysis-content p {
    font-size: 13px; color: #c8c8d8; margin: 8px 0;
    line-height: 1.7;
  }
  .analysis-content li {
    font-size: 13px; color: #c8c8d8;
    margin: 4px 0 4px 20px; line-height: 1.6;
    list-style: disc;
  }
  .analysis-content strong { color: #e8e8f0; }
  .analysis-content em { color: #a0a0b8; }

  /* Tables */
  .analysis-content table {
    width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px;
  }
  .analysis-content th {
    background: #1e1e38; color: #c0c0d8; padding: 8px 12px;
    border: 1px solid #2a2a3e; text-align: left; font-weight: 600;
  }
  .analysis-content td {
    padding: 8px 12px; border: 1px solid #2a2a3e; color: #d0d0e0;
  }
  .analysis-content tr:nth-child(even) td { background: rgba(255,255,255,0.02); }

  /* Math */
  .math-block { margin: 16px 0; text-align: center; overflow-x: auto; }
  .math-inline { }

  /* Relevance badge */
  .relevance-alta { color: #22c55e; }
  .relevance-media { color: #eab308; }
  .relevance-bassa { color: #ef4444; }

  /* Footer */
  .report-footer {
    margin-top: 32px; padding-top: 16px;
    border-top: 1px solid #2a2a3e;
    font-size: 11px; color: #6b6b80;
    display: flex; justify-content: space-between;
  }

  @media print {
    body { background: white; color: #1a1a2e; max-width: 100%; }
    .analysis-content { background: #f8f9fc; border-color: #e2e8f0; }
    .keywords-section { background: #f8f9fc; border-color: #e2e8f0; }
    .analysis-content h3 { color: #4f46e5; border-color: #e2e8f0; }
    .analysis-content p, .analysis-content li { color: #374151; }
    .report-footer { color: #9ca3af; border-color: #e2e8f0; }
  }
</style>
</head>
<body>

<div class="report-header">
  <div class="report-title">{{ paper.title }}
    {% if mode %}<span style="display:inline-block;font-size:11px;font-weight:700;padding:2px 8px;border-radius:4px;margin-left:10px;vertical-align:middle;{% if mode == 'deep' %}background:#7e22ce;color:#fff{% elif mode == 'summary' %}background:#d97706;color:#fff{% elif mode == 'extended' %}background:#b91c1c;color:#fff{% else %}background:#1d4ed8;color:#fff{% endif %}">{% if mode == 'extended' %}EXT.ABS{% else %}{{ mode.upper() }}{% endif %}</span>{% endif %}
  </div>
  <div class="report-meta">
    {% if paper.doi %}
    <span class="meta-label">DOI</span>
    <span><a href="https://doi.org/{{ paper.doi }}" target="_blank">{{ paper.doi }}</a></span>
    {% endif %}
    {% if paper.journal %}
    <span class="meta-label">Journal</span>
    <span>{{ paper.journal }}</span>
    {% endif %}
    <span class="meta-label">Date</span>
    <span>{{ paper.publication_date or 'N/A' }}</span>
    <span class="meta-label">Type</span>
    <span>{{ paper.paper_type }}</span>
    {% if authors %}
    <span class="meta-label">Authors</span>
    <span>{{ authors }}</span>
    {% endif %}
    {% if topics %}
    <span class="meta-label">Topics</span>
    <span>{{ topics }}</span>
    {% endif %}
    {% if sources %}
    <span class="meta-label">Sources</span>
    <span>{{ sources }}</span>
    {% endif %}
  </div>
</div>

<!-- Keywords Section -->
<div class="keywords-section">
  <div class="keywords-title">Keywords</div>
  <div>
    {% for kw in keyword_tags %}
    <span class="keyword-tag" style="background: {{ kw.bg }}; color: {{ kw.color }};">{{ kw.keyword }}</span>
    {% endfor %}
  </div>

  {% if keyword_categories %}
  <div class="keyword-category">
    {% for cat_name, cat_info in keyword_categories.items() %}
    <div class="category-label" style="color: {{ cat_info.color }};">
      <span class="category-dot" style="background: {{ cat_info.color }};"></span>
      {{ cat_name }}: {{ cat_info.keywords | join(', ') }}
    </div>
    {% endfor %}
  </div>
  {% endif %}
</div>

<!-- Analysis Content -->
<div class="analysis-content">
  {{ analysis_html | safe }}
</div>

<div class="report-footer">
  <span>{{ pdf_footer_text }}</span>
  <span>{{ generated_at }}</span>
</div>

</body>
</html>"""


def build_keyword_data(keywords: list[str]) -> tuple[list[dict], dict]:
    """Build keyword tags with colors and category grouping."""
    tags = []
    categories: dict[str, dict] = {}

    for kw in keywords:
        cat_name, color, bg = categorize_keyword(kw)
        tags.append({"keyword": kw, "color": color, "bg": bg, "category": cat_name})

        if cat_name not in categories:
            categories[cat_name] = {"color": color, "keywords": []}
        categories[cat_name]["keywords"].append(kw)

    return tags, categories


async def get_paper_data(db: AsyncSession, paper_id: int) -> dict | None:
    """Fetch full paper data for report generation."""
    result = await db.execute(
        select(Paper).where(Paper.id == paper_id)
    )
    paper = result.scalar_one_or_none()
    if not paper:
        return None

    # Get authors
    from app.models.paper import Author, PaperAuthor
    authors_result = await db.execute(
        select(Author)
        .join(PaperAuthor)
        .where(PaperAuthor.paper_id == paper_id)
        .order_by(PaperAuthor.position)
    )
    authors = [a.name for a in authors_result.scalars().all()]

    # Get topics
    topics_result = await db.execute(
        select(Topic)
        .join(PaperTopic)
        .where(PaperTopic.paper_id == paper_id)
    )
    topics = [t.name for t in topics_result.scalars().all()]

    # Get sources
    sources_result = await db.execute(
        select(PaperSource).where(PaperSource.paper_id == paper_id)
    )
    sources = [s.source_name for s in sources_result.scalars().all()]

    return {
        "paper": paper,
        "authors": ", ".join(authors) if authors else None,
        "topics": ", ".join(topics) if topics else None,
        "sources": ", ".join(sources) if sources else None,
    }


def _clean_stray_latex(text: str) -> str:
    """Clean LaTeX remnants in plain text that aren't wrapped in $...$."""
    # Replace \| with | (norm notation)
    text = text.replace('\\|', '|')
    # Replace \hat{x} → x̂, \bar{x} → x̄, \tilde{x} → x̃
    text = re.sub(r'\\hat\{(\w)\}', r'\1̂', text)
    text = re.sub(r'\\bar\{(\w)\}', r'\1̄', text)
    text = re.sub(r'\\tilde\{(\w)\}', r'\1̃', text)
    # Common Greek letters in plain text
    greek = {
        '\\alpha': 'α', '\\beta': 'β', '\\gamma': 'γ', '\\delta': 'δ',
        '\\epsilon': 'ε', '\\theta': 'θ', '\\lambda': 'λ', '\\mu': 'μ',
        '\\sigma': 'σ', '\\pi': 'π', '\\phi': 'φ', '\\omega': 'ω',
        '\\Delta': 'Δ', '\\Sigma': 'Σ', '\\Omega': 'Ω',
    }
    for latex, uni in greek.items():
        text = text.replace(latex, uni)
    # Common operators
    ops = {
        '\\cdot': '·', '\\times': '×', '\\leq': '≤', '\\geq': '≥',
        '\\neq': '≠', '\\approx': '≈', '\\infty': '∞', '\\sum': 'Σ',
        '\\prod': 'Π', '\\int': '∫', '\\partial': '∂', '\\nabla': '∇',
        '\\rightarrow': '→', '\\leftarrow': '←', '\\Rightarrow': '⇒',
        '\\forall': '∀', '\\exists': '∃', '\\in': '∈',
        '\\ell': 'ℓ', '\\quad': ' ', '\\,': '', '\\;': '',
    }
    for latex, uni in ops.items():
        text = text.replace(latex, uni)
    # \frac{a}{b} → (a)/(b) in plain text
    text = re.sub(r'\\frac\{([^}]+)\}\{([^}]+)\}', r'(\1)/(\2)', text)
    # \sqrt{x} → √(x)
    text = re.sub(r'\\sqrt\{([^}]+)\}', r'√(\1)', text)
    # \text{...}, \mathrm{...}, \mathbb{...} → just the content
    text = re.sub(r'\\(?:text|mathrm|mathbb|mathcal)\{([^}]+)\}', r'\1', text)
    # Superscripts and subscripts in plain text
    text = re.sub(r'\^\{([^}]+)\}', r'⁽\1⁾', text)
    text = re.sub(r'_\{([^}]+)\}', r'₍\1₎', text)
    # Remove remaining unknown \commands but keep the text after
    text = re.sub(r'\\[a-zA-Z]+(?:\{([^}]*)\})?', r'\1', text)
    # Clean stray braces
    text = text.replace('{', '').replace('}', '')
    return text


def render_paper_report(paper_data: dict, analysis_text: str, engine: str = "Claude Opus", mode: str = "") -> str:
    """Render the HTML report for a single paper."""
    paper = paper_data["paper"]
    keywords = paper.keywords or []

    keyword_tags, keyword_categories = build_keyword_data(keywords)
    # Strip fenced code blocks that Claude sometimes wraps the output in
    clean_text = analysis_text
    if clean_text.strip().startswith("```"):
        clean_text = re.sub(r'^```\w*\n?', '', clean_text.strip())
        if clean_text.endswith("```"):
            clean_text = clean_text[:-3]
    # Clean stray LaTeX in plain text (not wrapped in $...$)
    clean_text = _clean_stray_latex(clean_text)
    analysis_html = markdown_to_html(clean_text)

    env = Environment(loader=BaseLoader(), autoescape=True)
    template = env.from_string(PAPER_REPORT_TEMPLATE)

    return template.render(
        paper=paper,
        authors=paper_data["authors"],
        topics=paper_data["topics"],
        sources=paper_data["sources"],
        engine=engine,
        mode=mode,
        keyword_tags=keyword_tags,
        keyword_categories=keyword_categories,
        analysis_html=analysis_html,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        pdf_footer_text=_pdf_footer_text_plain(),
    )


def _get_next_version(paper_id: int, mode: str) -> int:
    """Get next version number for a paper+mode combination."""
    reports_dir = Path(settings.reports_path) / "analysis"
    if not reports_dir.exists():
        return 1
    existing = list(reports_dir.glob(f"analysis_{mode}_{paper_id}_v*.html"))
    if not existing:
        return 1
    versions = []
    for p in existing:
        # Extract version from filename: analysis_quick_461_v3.html
        try:
            v = int(p.stem.rsplit("_v", 1)[1])
            versions.append(v)
        except (ValueError, IndexError):
            continue
    return max(versions, default=0) + 1


def save_report(html: str, paper_id: int, mode: str = "quick", version: int | None = None) -> Path:
    """Save HTML report to disk with versioned naming. Returns HTML path."""
    reports_dir = Path(settings.reports_path) / "analysis"
    reports_dir.mkdir(parents=True, exist_ok=True)

    if version is None:
        version = _get_next_version(paper_id, mode)

    basename = f"analysis_{mode}_{paper_id}_v{version}"
    path = reports_dir / f"{basename}.html"
    path.write_text(html, encoding="utf-8")
    logger.info(f"Report saved: {path}")
    return path


def save_markdown(analysis_text: str, paper_id: int, mode: str, paper_data: dict, version: int | None = None) -> Path:
    """Save analysis as Markdown file with versioned naming."""
    reports_dir = Path(settings.reports_path) / "analysis"
    reports_dir.mkdir(parents=True, exist_ok=True)

    if version is None:
        version = _get_next_version(paper_id, mode)

    basename = f"analysis_{mode}_{paper_id}_v{version}"
    path = reports_dir / f"{basename}.md"

    paper = paper_data["paper"]
    header = f"""---
title: "{paper.title}"
paper_id: {paper_id}
mode: {mode}
version: {version}
doi: {paper.doi or "N/A"}
journal: {paper.journal or "N/A"}
date: {paper.publication_date or "N/A"}
generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
---

"""
    path.write_text(header + analysis_text, encoding="utf-8")
    logger.info(f"Markdown saved: {path}")
    return path


def _markdown_to_latex(text: str) -> str:
    """Convert Markdown analysis text to LaTeX body content, with tables and math."""
    # Protect math from escaping: extract $...$ and $$...$$ first
    math_blocks: list[str] = []
    math_inlines: list[str] = []

    def _save_block(m: re.Match) -> str:
        math_blocks.append(m.group(1))
        return f"%%MATHBLOCK{len(math_blocks) - 1}%%"

    def _save_inline(m: re.Match) -> str:
        math_inlines.append(m.group(1))
        return f"%%MATHINLINE{len(math_inlines) - 1}%%"

    text = re.sub(r'\$\$(.+?)\$\$', _save_block, text, flags=re.DOTALL)
    text = re.sub(r'(?<!\$)\$([^\$\n]+?)\$(?!\$)', _save_inline, text)

    lines = text.split("\n")
    result = []
    in_list = False
    in_table = False
    table_lines: list[str] = []

    for line in lines:
        stripped = line.strip()

        # Detect table rows (pipes)
        is_table_row = stripped.startswith("|") and stripped.endswith("|") and stripped.count("|") >= 3
        is_separator = is_table_row and re.match(r'^\|[\s\-:|]+\|$', stripped)

        if is_table_row:
            if in_list:
                result.append("\\end{itemize}")
                in_list = False
            if not in_table:
                in_table = True
                table_lines = []
            if not is_separator:
                table_lines.append(stripped)
            continue
        elif in_table:
            # End of table — render it
            result.append(_render_latex_table(table_lines))
            in_table = False
            table_lines = []

        # Headers
        if stripped.startswith("### "):
            if in_list:
                result.append("\\end{itemize}")
                in_list = False
            header_text = _latex_inline(stripped[4:])
            result.append(f"\\subsubsection{{{header_text}}}")
            continue
        if stripped.startswith("## "):
            if in_list:
                result.append("\\end{itemize}")
                in_list = False
            header_text = _latex_inline(stripped[3:])
            result.append(f"\\subsection{{{header_text}}}")
            continue
        if stripped.startswith("# "):
            if in_list:
                result.append("\\end{itemize}")
                in_list = False
            header_text = _latex_inline(stripped[2:])
            result.append(f"\\section{{{header_text}}}")
            continue

        # List items
        if stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                result.append("\\begin{itemize}")
                in_list = True
            item_text = _latex_inline(stripped[2:])
            result.append(f"  \\item {item_text}")
            continue

        # Empty line
        if not stripped:
            if in_list:
                result.append("\\end{itemize}")
                in_list = False
            result.append("")
            continue

        # Regular paragraph
        if in_list:
            result.append("\\end{itemize}")
            in_list = False
        result.append(_latex_inline(stripped))

    if in_list:
        result.append("\\end{itemize}")
    if in_table:
        result.append(_render_latex_table(table_lines))

    output = "\n".join(result)

    # Restore math
    for i, formula in enumerate(math_blocks):
        output = output.replace(f"%%MATHBLOCK{i}%%", f"\n\\[\n{formula}\n\\]\n")
    for i, formula in enumerate(math_inlines):
        output = output.replace(f"%%MATHINLINE{i}%%", f"${formula}$")

    return output


def _render_latex_table(table_lines: list[str]) -> str:
    """Convert parsed Markdown table lines to LaTeX tabular."""
    if not table_lines:
        return ""

    # Parse cells
    rows = []
    for line in table_lines:
        cells = [c.strip() for c in line.strip("|").split("|")]
        rows.append(cells)

    if not rows:
        return ""

    num_cols = max(len(r) for r in rows)
    col_spec = "|".join(["l"] * num_cols)

    tex = "\\begin{table}[h]\n\\centering\n"
    tex += f"\\begin{{tabular}}{{|{col_spec}|}}\n\\hline\n"

    for i, row in enumerate(rows):
        # Pad row to num_cols
        while len(row) < num_cols:
            row.append("")
        escaped = [_latex_inline(cell) for cell in row]
        tex += " & ".join(escaped)
        tex += " \\\\\n\\hline\n"

    tex += "\\end{tabular}\n\\end{table}"
    return tex


def _latex_inline(text: str) -> str:
    """Convert inline Markdown formatting to LaTeX, preserving math placeholders."""
    # Don't escape inside math placeholders
    parts = re.split(r'(%%MATH(?:BLOCK|INLINE)\d+%%)', text)
    result_parts = []
    for part in parts:
        if part.startswith("%%MATH"):
            result_parts.append(part)
        else:
            # Escape LaTeX special chars (but not $ for formulas, not \ for existing commands)
            for char in ['&', '%', '#', '_']:
                part = part.replace(char, f"\\{char}")
            # Bold: **text** → \textbf{text}
            part = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', part)
            # Italic: *text* → \textit{text}
            part = re.sub(r'\*(.+?)\*', r'\\textit{\1}', part)
            # Inline code: `text` → \texttt{text}
            part = re.sub(r'`(.+?)`', r'\\texttt{\1}', part)
            result_parts.append(part)
    text = "".join(result_parts)
    return text


def save_latex(analysis_text: str, paper_id: int, mode: str, paper_data: dict, engine: str = "Claude Opus 4.6", version: int | None = None) -> Path:
    """Save analysis as LaTeX file with versioned naming."""
    reports_dir = Path(settings.reports_path) / "analysis"
    reports_dir.mkdir(parents=True, exist_ok=True)

    if version is None:
        version = _get_next_version(paper_id, mode)

    basename = f"analysis_{mode}_{paper_id}_v{version}"
    path = reports_dir / f"{basename}.tex"

    paper = paper_data["paper"]
    authors = paper_data.get("authors", "")
    body = _markdown_to_latex(analysis_text)

    # Escape strings for LaTeX (must be outside f-string for Python 3.11)
    def _esc(s: str) -> str:
        return s.replace('&', '\\&').replace('%', '\\%').replace('#', '\\#').replace('_', '\\_')

    title_escaped = _esc(paper.title)
    journal_escaped = _esc(paper.journal or "N/A")
    authors_escaped = _esc(authors or "")

    # Sober, rigorous full-width template for all analysis modes
    tex = f"""\\documentclass[11pt,a4paper]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage[T1]{{fontenc}}
\\usepackage[italian]{{babel}}
\\usepackage{{geometry}}
\\geometry{{a4paper,top=2.5cm,bottom=2.5cm,left=2.8cm,right=2.8cm}}
\\usepackage{{hyperref}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{enumitem}}
\\usepackage{{lmodern}}
\\usepackage{{microtype}}
\\usepackage{{titlesec}}
\\usepackage{{xcolor}}

\\hypersetup{{colorlinks=false,pdfborder={{0 0 0}}}}

\\setcounter{{secnumdepth}}{{0}}

% Section formatting: bold small caps, no numbering
\\titleformat{{\\section}}{{\\normalfont\\large\\bfseries\\scshape}}{{}}{{0pt}}{{}}[\\vspace{{0.2em}}]
\\titleformat{{\\subsection}}{{\\normalfont\\normalsize\\bfseries}}{{}}{{0pt}}{{}}[\\vspace{{0.1em}}]
\\titlespacing*{{\\section}}{{0pt}}{{1.4em}}{{0.5em}}

\\pagestyle{{plain}}

\\setlength{{\\parskip}}{{0.4em}}
\\setlength{{\\parindent}}{{0pt}}

\\begin{{document}}

\\begin{{center}}
{{\\Large\\bfseries {title_escaped}}}\\\\[0.6em]
{{\\normalsize {authors_escaped}}}\\\\[0.4em]
{{\\small {paper.publication_date or "N/A"} \\quad\\textbar\\quad {journal_escaped} \\quad\\textbar\\quad DOI: {paper.doi or "N/A"}}}
\\end{{center}}

\\vspace{{0.8em}}

{body}

\\vfill
\\hrule
\\vspace{{0.4em}}
{{\\footnotesize\\textcolor{{gray}}{{{_pdf_footer_text()}}}}}

\\end{{document}}
"""
    path.write_text(tex, encoding="utf-8")
    logger.info(f"LaTeX saved: {path}")
    return path


PDF_OVERRIDE_CSS = """
    body { background: white !important; color: #1a1a2e !important; }
    .report-header { border-color: #d1d5db !important; }
    .report-title { color: #111827 !important; }
    .report-meta { color: #374151 !important; }
    .meta-label { color: #6b7280 !important; }
    .keywords-section { background: #f9fafb !important; border-color: #e5e7eb !important; }
    .keywords-title { color: #374151 !important; }
    .analysis-content { background: #ffffff !important; border-color: #e5e7eb !important; }
    .analysis-content h3 { color: #4338ca !important; border-color: #e5e7eb !important; }
    .analysis-content p { color: #1f2937 !important; }
    .analysis-content li { color: #1f2937 !important; }
    .analysis-content strong { color: #111827 !important; }
    .analysis-content em { color: #4b5563 !important; }
    .report-footer { color: #6b7280 !important; border-color: #e5e7eb !important; }
    .keyword-category { border-color: #e5e7eb !important; }
    .category-label { color: #374151 !important; }
    a { color: #4338ca !important; }
    .analysis-content th { background: #f3f4f6 !important; color: #1f2937 !important; border-color: #d1d5db !important; }
    .analysis-content td { color: #1f2937 !important; border-color: #d1d5db !important; }
    .analysis-content tr:nth-child(even) td { background: #f9fafb !important; }
"""


def generate_pdf(html_path: Path, tex_path: Path | None = None) -> Path | None:
    """Generate PDF. Uses pdflatex from .tex if available, falls back to weasyprint from .html."""
    pdf_path = html_path.with_suffix(".pdf")

    # Try pdflatex first (best formula rendering)
    if tex_path and tex_path.exists():
        try:
            import subprocess
            abs_tex = Path(tex_path).resolve()
            abs_dir = abs_tex.parent
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", str(abs_tex.name)],
                capture_output=True, text=True, timeout=60,
                cwd=str(abs_dir),
            )
            tex_pdf = abs_tex.with_suffix(".pdf")
            if tex_pdf.exists() and tex_pdf.stat().st_size > 0:
                # Copy to expected path if different
                abs_pdf = Path(pdf_path).resolve()
                if tex_pdf != abs_pdf:
                    import shutil
                    shutil.copy2(str(tex_pdf), str(abs_pdf))
                # Clean up LaTeX aux files
                for ext in [".aux", ".log", ".out", ".toc"]:
                    aux = abs_tex.with_suffix(ext)
                    if aux.exists():
                        aux.unlink()
                logger.info(f"PDF generated via pdflatex: {pdf_path}")
                return pdf_path
            else:
                logger.warning(f"pdflatex did not produce PDF. Return code: {result.returncode}")
                # Log first few errors
                for line in result.stdout.split('\n'):
                    if line.startswith('!'):
                        logger.warning(f"  pdflatex: {line}")
        except FileNotFoundError:
            logger.warning("pdflatex not found, falling back to weasyprint")
        except subprocess.TimeoutExpired:
            logger.warning("pdflatex timed out, falling back to weasyprint")
        except Exception as e:
            logger.warning(f"pdflatex failed: {e}, falling back to weasyprint")

    # Fallback: weasyprint from HTML
    import os
    if "DYLD_FALLBACK_LIBRARY_PATH" not in os.environ:
        os.environ["DYLD_FALLBACK_LIBRARY_PATH"] = "/opt/homebrew/lib"
    try:
        from weasyprint import HTML, CSS
        html_doc = HTML(filename=str(html_path))
        css_override = CSS(string=PDF_OVERRIDE_CSS)
        html_doc.write_pdf(str(pdf_path), stylesheets=[css_override])
        logger.info(f"PDF generated via weasyprint: {pdf_path}")
        return pdf_path
    except ImportError:
        logger.warning("weasyprint not installed, skipping PDF generation")
        return None
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        return None
